[#3]: align loading script conf and variable names with convention

diff --git a/code/bin/dd-build-cont-images b/code/bin/dd-build-cont-images
--- a/code/bin/dd-build-cont-images
+++ b/code/bin/dd-build-cont-images
@@ -57,13 +57,34 @@ if ! get_conf_file_arg "${@}"        ; then exit 1; fi
 # -----------------------------------------------------------------------------
 # load script configuration
 
-# shellcheck disable=SC2154
-conf="$(yq r -j "${conf_file}")"
+echo
 
-local_namespace="$(jq -r '.local_namespace'   <<< "${conf}")"
-image_confs="$(    jq -r '.images'            <<< "${conf}")"
-rel_target_root="$(jq -r '.path_to_proj_root' <<< "${conf}")"
-path_to_secrets="$(jq -r '.path_to_secrets'   <<< "${conf}")"
+echo -n 'Load script configuration file: '
+# shellcheck disable=SC2154
+if output="$(yq read "${conf_file}" --tojson 2>&1)"
+then
+    echo 'OK'
+    config="${output}"
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
+
+echo -n 'Extract script configuration attributes: '
+for attr in images local_namespace path_to_proj_root path_to_secrets
+do
+    # https://unix.stackexchange.com/a/68349
+    declare "${attr}"="$(jq -r ".${attr}" <<< "${config}")"
+    # https://unix.stackexchange.com/a/41418
+    if [ -z "${!attr}" ] || [ "${!attr}" = 'null' ]
+    then
+        echo 'ERROR'
+        echo "Failed to get ${attr} attribute from configuration"
+        exit 1
+    fi
+done
+echo 'OK'
 
 
 # -----------------------------------------------------------------------------
@@ -75,8 +96,8 @@ then
     exit 1
 fi
 
-# absolute, canonical path to TARGET project root
-path_to_target_root="$(realpath "${path_to_conf_folder}/${rel_target_root}")"
+# absolute, canonical path to target project root
+path_to_target_root="$(realpath "${path_to_conf_folder}/${path_to_proj_root}")"
 
 # absolute, canonical path to secrets folder in TARGET project
 # NOTE: not using realpath as this folder usually doesn't exist yet
@@ -109,7 +130,7 @@ then
     fi
 fi
 
-if ! image_names="$(jq -r 'keys[]' <<< "${image_confs}" | sort)"
+if ! image_names="$(jq -r 'keys[]' <<< "${images}" | sort)"
 then
     exit 1
 fi
@@ -119,7 +140,7 @@ do
     echo "container image name: ${image_name}"
     echo
 
-    if ! image_conf="$(jq -r ".\"${image_name}\"" <<< "${image_confs}")"
+    if ! image_conf="$(jq -r ".\"${image_name}\"" <<< "${images}")"
     then
         exit 1
     fi
