[#3]: use a single container image tag: <stage>-<hash|semver>

diff --git a/code/bin/dd-dt-upload-cont-images-to-gitlab b/code/bin/dd-dt-upload-cont-images-to-gitlab
--- a/code/bin/dd-dt-upload-cont-images-to-gitlab
+++ b/code/bin/dd-dt-upload-cont-images-to-gitlab
@@ -126,12 +126,7 @@ do
         exit 1
     fi
 
-    if ! image_tag_stage="$( jq -r '.image_tag_stage'  <<< "${image_conf}")"
-    then
-        exit 1
-    fi
-
-    if ! image_tag_second="$(jq -r '.image_tag_second' <<< "${image_conf}")"
+    if ! image_tag="$(jq -r '.image_tag' <<< "${image_conf}")"
     then
         exit 1
     fi
@@ -139,36 +134,33 @@ do
     # shellcheck disable=SC2154
     repo_uri="${gitlab_reg_url}/${gitlab_namespace}/${image_name}"
 
-    for image_tag in "${image_tag_second}" "${image_tag_stage}"
-    do
-        repo_tag="${repo_uri}:${image_tag}"
-        # shellcheck disable=SC2154
-        local_tag="${local_namespace}/${image_name}:${image_tag}"
+    repo_tag="${repo_uri}:${image_tag}"
+    # shellcheck disable=SC2154
+    local_tag="${local_namespace}/${image_name}:${image_tag}"
 
-        echo -n 'Tag Docker container image with repository info: '
-        if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
-        then
-            echo 'OK'
-            echo
-        else
-            echo 'ERROR'
-            echo "${output}"
-            exit 1
-        fi
-
-        echo 'Push Docker container image to repository:'
-        if ! docker push "${repo_tag}"
-        then
-            exit 1
-        fi
-
+    echo -n 'Tag Docker container image with repository info: '
+    if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
+    then
+        echo 'OK'
         echo
-        echo 'Remove repository info tag from Docker container:'
-        if ! docker rmi "${repo_tag}"
-        then
-            exit 1
-        fi
-    done
+    else
+        echo 'ERROR'
+        echo "${output}"
+        exit 1
+    fi
+
+    echo 'Push Docker container image to repository:'
+    if ! docker push "${repo_tag}"
+    then
+        exit 1
+    fi
+
+    echo
+    echo 'Remove repository info tag from Docker container:'
+    if ! docker rmi "${repo_tag}"
+    then
+        exit 1
+    fi
 
     echo
     echo "container image ${image_name} upload complete"
