[#4]: use role ID and secret ID from conf instead of root token to auth;
+ save secrets obtained from vault into per-path file, not one big one
+ pass path to secrets to docker when building container
+ add a copy of check_vault_response, taken from VaultTools > vault lib
+ adapt to conv agreed with MailFlow Database on rel/abs temp paths

diff --git a/code/bin/dd-dt-build-image b/code/bin/dd-dt-build-image
--- a/code/bin/dd-dt-build-image
+++ b/code/bin/dd-dt-build-image
@@ -18,6 +18,46 @@ echo
 
 
 # -----------------------------------------------------------------------------
+# define functions: http://stackoverflow.com/a/6212408
+
+function check_vault_response
+{
+    # NOTE: see also VaultTools > dd-vt-vault.lib > check_response
+
+    if [ $# -ne 1 ]
+    then
+        # get function name: https://stackoverflow.com/a/1835958
+        echo "Usage: ${FUNCNAME[0]} <vault response>" 2>&1
+        return 1
+    fi
+
+    # TODO: validate arguments
+
+    # response from vault instance
+    response="${1}"
+
+    if [ -z "${response}" ]
+    then
+        return 0
+    fi
+
+    jq_err='if   .errors   and (.errors   | length) > 0 then .errors[] '`
+          `'elif .warnings and (.warnings | length) > 0 then .warnings[] '`
+          `'else empty end'
+
+    err_resp="$(jq -r "${jq_err}" <<< "${response}")"
+
+    if [ -z "${err_resp}" ]
+    then
+        return 0
+    else
+        echo "${err_resp}" 2>&1
+        return 1
+    fi
+}
+
+
+# -----------------------------------------------------------------------------
 # configure script parameters
 
 # absolute path to BashLib library file
@@ -25,7 +65,7 @@ path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 
 # array with alphabetical list of tools called by this script
 # shellcheck disable=SC2034
-req_tools=('curl' 'docker' 'jq' 'realpath')
+req_tools=('curl' 'docker' 'jo' 'jq' 'realpath')
 
 # array with paths to append to PATH
 # shellcheck disable=SC2034
@@ -84,59 +124,110 @@ if ! get_attrs_from_yaml_file "${conf_file}" attrs opt_attrs; then exit 1; fi
 path_to_conf_folder="$(dirname "${conf_file}")"
 
 # absolute, canonical path to target project root
+# TODO: (globally) rename target root to client root
 # shellcheck disable=SC2154
 path_to_target_root="$(realpath "${path_to_conf_folder}/${path_to_client_root}")"
 
 
 # -----------------------------------------------------------------------------
-# build Docker container images
-
-
-if ! pushd "${path_to_target_root}" > /dev/null
-then
-    echo "Failed to pushd to target project root ${path_to_target_root}"
-    exit 1
-fi
-
-
-echo
+# get secrets required to build Docker container image from vault
 
 # shellcheck disable=SC2154
 if [ -n "${vault}" ]
 then
     path_to_secrets="$(jq -r '.path_to_secrets' <<< "${vault}")"
+    role_id="$(        jq -r '.role_id'         <<< "${vault}")"
+    secret_id="$(      jq -r '.secret_id'       <<< "${vault}")"
     vault_host="$(     jq -r '.vault_host'      <<< "${vault}")"
     vault_root="$(     jq -r '.vault_root'      <<< "${vault}")"
     vault_paths="$(    jq    '.vault_paths'     <<< "${vault}")"
 
-    # absolute, canonical path to secrets folder in TARGET project
-    path_to_secrets="$(realpath "${path_to_target_root}/${path_to_secrets}")"
+    # url path to log into vault using role + secret ID, relative to vault_root:
+    # https://learn.hashicorp.com/vault/identity-access-management/ ...
+    #  ... approle#step-4-login-with-roleid-secretid
+    url_path='v1/auth/approle/login'
 
-    echo "Fetch secrets from vault at ${vault_host}/${vault_root}:"
+    full_url="${vault_host}/${url_path}"
+    req_data="$(jo role_id="${role_id}" secret_id="${secret_id}")"
 
-    # -------------------------------------------------
-    # TODO: get role ID and secret ID from conf instead
-    # -------------------------------------------------
+    # NOTE: useful during development and debugging
+    # TODO: if using this, redact any sensitive data;
+    # for example, this exposes vault credentials in log output
+    # echo
+    # echo 'full curl command line:'
+    # echo "curl --data ${req_data} --request POST ${curl_args[*]} ${full_url}"
+    echo -n 'log into vault: '
+    if output="$(curl --data "${req_data}" \
+                      --request POST "${curl_args[@]}" "${full_url}" 2>&1)"
+    then
+        if err_resp="$(check_vault_response "${output}" 2>&1)"
+        then
+            echo 'OK'
+            json_response="${output}"
+        else
+            echo 'ERROR'
+            echo "${err_resp}"
+            exit 1
+        fi
+    else
+        echo 'ERROR'
+        echo "${output}"
+        exit 1
+    fi
 
-    # TODO: this duplicates code from .../cicd/bin/deploy used
-    # in many projects; refactor out to function or so and re-use
-    echo -n "  Get vault token from ${path_to_vault_token}: "
-    if output="$(cat "${path_to_vault_token}" 2>&1)"
+    # TODO: why is this token an orphan ?
+
+    # echo 'json_response:'
+    # jq '.' <<< "${json_response}"
+    # sample output:
+    # json_response:
+    # {
+    #   "request_id": "f1e019fd-a306-730e-cb9b-fda8f3a7a400",
+    #   "lease_id": "",
+    #   "renewable": false,
+    #   "lease_duration": 0,
+    #   "data": null,
+    #   "wrap_info": null,
+    #   "warnings": null,
+    #   "auth": {
+    #     "client_token": "<not shown here>",
+    #     "accessor": "<not shown here>",
+    #     "policies": [
+    #       "projects/mailflow/database/feature/builder"
+    #     ],
+    #     "token_policies": [
+    #       "projects/mailflow/database/feature/builder"
+    #     ],
+    #     "metadata": {
+    #       "role_name": "projects_mailflow_database_feature_builder"
+    #     },
+    #     "lease_duration": 2764800,
+    #     "renewable": true,
+    #     "entity_id": "e9976020-98e0-e6a9-76f9-31f902b912db",
+    #     "token_type": "service",
+    #     "orphan": true
+    #   }
+    # }
+
+    echo -n 'extract token from response: '
+    if output="$(jq -r '.auth.client_token' <<< "${json_response}" 2>&1)"
     then
         vault_token="${output}"
         echo 'OK'
     else
         echo 'ERROR'
-        echo "  ${output}"
+        echo "${output}"
         exit 1
     fi
 
     header_value="X-Vault-Token: ${vault_token}"
     curl_args+=("--header" "${header_value}")
 
-    mapfile -t vault_paths < <(jq -r '.[]' <<< "${vault_paths}")
-    secrets_json=''
+    echo "Fetch secrets from vault at ${vault_host}/${vault_root}:"
 
+    mapfile -t vault_paths < <(jq -r '.[]' <<< "${vault_paths}")
+
+    # TODO: handle case of no vault paths
     for vault_path in "${vault_paths[@]}"
     do
         echo "  ${vault_path}:"
@@ -144,21 +235,18 @@ then
         # shellcheck disable=SC2154
         full_url="${vault_host}/${vault_root}/${vault_path}"
 
-        # NOTE: useful during development and debugging
-        # TODO: redact any sensitive data in log output
-        # msg="    full 'curl' command line:"$'\n'
-        # msg+="      curl --request GET ${curl_args[*]} ${full_url}"
-        # echo "${msg}"
-
-        echo -n '    request credentials from vault: '
-        # TODO: this displays vault token and retrieved password in log
-        # echo
-        # echo 'full curl command line:'
-        # echo "curl --request GET ${curl_args[*]} ${full_url}"
+        echo -n '    get secret from vault: '
         if output="$(curl --request GET "${curl_args[@]}" "${full_url}" 2>&1)"
         then
-            echo 'OK'
-            json_response="${output}"
+            if err_resp="$(check_vault_response "${output}" 2>&1)"
+            then
+                echo 'OK'
+                json_response="${output}"
+            else
+                echo 'ERROR'
+                echo "    ${err_resp}"
+                exit 1
+            fi
         else
             echo 'ERROR'
             echo "    ${output}"
@@ -170,61 +258,113 @@ then
         # sample output:
         # json_response:
         # {
-        #   "request_id": "4a2efccb-2c3b-1e9c-5a15-21bca4b3af17",
+        #   "request_id": "925051f3-f631-d90f-7883-17ef95a057e0",
         #   "lease_id": "",
         #   "renewable": false,
         #   "lease_duration": 0,
         #   "data": {
-        #     "password": "<not shown here>",
-        #     "username": "<not shown here>"
+        #     "data": {
+        #       "database_admin_password": "<not shown here>",
+        #       "database_admin_username": "<not shown here>"
+        #     },
+        #     "metadata": {
+        #       "created_time": "2020-06-26T21:57:18.167202575Z",
+        #       "deletion_time": "",
+        #       "destroyed": false,
+        #       "version": 6
+        #     }
         #   },
         #   "wrap_info": null,
         #   "warnings": null,
         #   "auth": null
         # }
-        #
-        # NOTE: attributes inside data (e.g. password, username)
-        # vary depending on what was uploaded to vault initially
 
-        # TODO: response is '.errors: []' if no contents
-        echo -n '    check vault response: '
-        output="$(jq '.errors' <<< "${json_response}")"
-        if [ "${output}" = 'null' ]
-        then
-            echo 'OK'
-        else
-            echo 'ERROR'
-            # TODO: align; add indent
-            jq -r '.[]' <<< "${output}"
-            exit 1
-        fi
+        # NOTE: .data.data properties are typically different for every path
 
-        echo -n '    get data from response: '
-        output="$(jq '.data' <<< "${json_response}")"
+        # TODO: .data.data ?!? SERIOUSLY ?!?
+        echo -n '    extract secrets data from response: '
+        output="$(jq '.data.data' <<< "${json_response}")"
         if [ "${output}" != 'null' ]
         then
-            json_data="${output}"
+            secrets_json="${output}"
             echo 'OK'
         else
             echo 'ERROR'
+            echo "    ${output}"
             exit 1
         fi
 
-        secrets_json+="${json_data}"
-    done
+        # echo 'secrets_json:'
+        # jq '.' <<< "${secrets_json}"
+        # sample output:
+        # secrets_json:
+        # {
+        #   "database_user_password": "<not shown here>",
+        #   "database_user_username": "<not shown here>"
+        # }
 
-    echo -n "  Save secrets to temp file: "
-    # https://stackoverflow.com/a/41218259
-    if output="$(jq -s 'add' <<< "${secrets_json}" \
-                  > "${path_to_secrets}/${secrets_filename}" 2>&1)"
-    then
-        echo 'OK'
-    else
-        echo 'ERROR'
-        echo "  ${output}"
-        exit 1
-    fi
+        # TODO: vault_paths is not a good property name; those are not actually
+        # vault paths, but titles for secrets grouped together in one yaml file
+        # in the local sec loc or at one <vault root>/<vault path> in Vault;
+        # conf example from Projects > MailFlow > Database > feature:
+        #   # path into vault where secrets are stored, relative to vault_host
+        #   vault_root: v1/kv-v2/data/Projects/MailFlow/Database/feature
+        #   # vault path for secrets, relative to vault_host/vault_root
+        #   vault_paths:
+        #   - database-admin-credentials
+        #   - database-reader-credentials
+        #   - database-root-credentials
+        #   - database-user-credentials
+        # so the conf might be partitioned and named suboptimally, but at least
+        # this prevents (to a certain extent) that two vault_paths with the
+        # same name are configured - which would cause the first temp file here
+        # to be overwritten by a second (with the same name)
+
+        # store group of secrets, e.g.
+        #   database_user_username, database_user_password
+        # in a temp folder underneath the client's project space root, e.g.
+        #   ~/DevBase/DesmoDyne/Projects/MailFlow/Database/ ...
+        #      ... tmp/build/ci-mailflow-database_dev/secrets/
+        # in a json temp file named after the vault path, e.g.
+        #   database-admin-credentials.json
+        # use json so those secrets can easily be consumed using e.g. jq
+
+        secrets_filename="${vault_path}.json"
+
+        # absolute, canonical path to secrets folder in client project
+        # NOTE: path_to_secrets will be re-used to build container
+        path_to_secrets_="${path_to_target_root}/${path_to_secrets}"
+
+        # NOTE: not creating the output folder; that is the client's job
+        # NOTE: using jq to pretty-print json, helps during development
+        echo -n "    save secrets data to temp file: "
+        if output="$(jq '.' <<< "${secrets_json}" \
+                      > "${path_to_secrets_}/${secrets_filename}" 2>&1)"
+        then
+            echo 'OK'
+        else
+            echo 'ERROR'
+            echo "    ${output}"
+            exit 1
+        fi
+    done
 fi
+
+
+# -----------------------------------------------------------------------------
+# build Docker container image
+
+echo
+echo 'build Docker container image:'
+echo
+
+
+if ! pushd "${path_to_target_root}" > /dev/null
+then
+    echo "Failed to pushd to target project root ${path_to_target_root}"
+    exit 1
+fi
+
 
 # shellcheck disable=SC2154
 if [ ! -f "${image_conf_path}" ]
@@ -239,6 +379,13 @@ fi
 # NOTE: =() is required to clear the array
 # when this loop is run the second time
 declare -a docker_args=()
+
+# if a vault conf was passed, Docker build
+# needs to know where the secrets files are
+if [ -n "${vault}" ]
+then
+    docker_args+=('--build-arg' "PATH_TO_SECRETS=${path_to_secrets}")
+fi
 
 # TODO: remove as soon as there is more than one item
 # shellcheck disable=SC2043
@@ -266,6 +413,7 @@ msg+=" --tag ${image_path}:${image_tag}"
 msg+=" $(pwd)"
 echo "${msg}"
 
+echo
 echo "Build ${image_name} with"
 echo "  $(realpath "${image_conf_path}"):"
 echo
@@ -287,5 +435,5 @@ then
 fi
 
 
-echo 'Docker container image build complete'
 echo
+echo 'Docker container image build complete'
