[#3]: don't exit, but continue upon error in loop; add TODO comment

diff --git a/code/bin/dd-dt-volume-backup b/code/bin/dd-dt-volume-backup
--- a/code/bin/dd-dt-volume-backup
+++ b/code/bin/dd-dt-volume-backup
@@ -97,6 +97,7 @@ then
 fi
 
 # TODO: stop containers before creating backup of their volumes ?
+# TODO: if any of the loops fail, continue and set failure script exit code
 
 for image_name in ${image_names}
 do
@@ -117,7 +118,7 @@ do
 
     if ! image_conf="$(jq -r ".\"${image_name}\"" <<< "${images}")"
     then
-        exit 1
+        continue
     fi
 
     echo -n 'Extract image properties from configuration: '
@@ -130,7 +131,7 @@ do
         then
             echo 'ERROR'
             echo "${output}"
-            exit 1
+            continue
         fi
 
         # TODO: distinguish between mandatory and optional attributes
@@ -141,7 +142,7 @@ do
         # then
         #     echo 'ERROR'
         #     echo "failed to get ${attr} attribute from configuration"
-        #     exit 1
+        #     continue
         # fi
     done
     echo 'OK'
@@ -186,7 +187,7 @@ do
     echo "  docker run ${docker_args[*]}"
 
     # docker displays container log as output
-    if ! docker run "${docker_args[@]}"; then exit 1; fi
+    if ! docker run "${docker_args[@]}"; then continue; fi
 
     echo "container image ${image_name} complete"
     echo
