[#4]: find <stage>-latest image tag; upload if it exists, warn if not

diff --git a/code/bin/dd-dt-upload-image-to-gitlab b/code/bin/dd-dt-upload-image-to-gitlab
--- a/code/bin/dd-dt-upload-image-to-gitlab
+++ b/code/bin/dd-dt-upload-image-to-gitlab
@@ -128,37 +128,60 @@ else
     exit 1
 fi
 
+# NOTE: need to determine if there is also an image with a <stage>-latest tag,
+# but docker doesn't seem to support filtering images by image ID :-(
+
+all_tags=("${image_tag}")
+
+local_name="${local_namespace}/${image_name}"
+repo_name="${gitlab_reg_url}/${gitlab_namespace}/${image_name}"
 
 # shellcheck disable=SC2154
-repo_uri="${gitlab_reg_url}/${gitlab_namespace}/${image_name}"
+local_tag="${local_name}:${image_tag}"
 
-repo_tag="${repo_uri}:${image_tag}"
-# shellcheck disable=SC2154
-local_tag="${local_namespace}/${image_name}:${image_tag}"
+stage="$(cut -d '-' -f 1 <<< "${image_tag}")"
+latest_tag="${local_name}:${stage}-latest"
 
-echo -n 'Tag Docker container image with repository info: '
-if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
+image_id="$( docker images "${local_tag}"  --format='{{.ID}}')"
+latest_id="$(docker images "${latest_tag}" --format='{{.ID}}')"
+
+if [ "${latest_id}" = "${image_id}" ]
 then
-    echo 'OK'
-    echo
+    all_tags+=("${stage}-latest")
 else
-    echo 'ERROR'
-    echo "${output}"
-    exit 1
+    echo "WARNING: failed to find an image with a ${stage}-latest tag"
 fi
 
-echo 'Push Docker container image to repository:'
-if ! docker push "${repo_tag}"
-then
-    exit 1
-fi
+for tag in "${all_tags[@]}"
+do
+    local_tag="${local_name}:${tag}"
+    # shellcheck disable=SC2154
+    repo_tag="${repo_name}:${tag}"
 
-echo
-echo 'Remove repository info tag from Docker container:'
-if ! docker rmi "${repo_tag}"
-then
-    exit 1
-fi
+    echo -n 'Tag Docker container image with repository info: '
+    if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
+    then
+        echo 'OK'
+        echo
+    else
+        echo 'ERROR'
+        echo "${output}"
+        exit 1
+    fi
+
+    echo "Push Docker container image to repository: ${local_tag}"
+    if ! docker push "${repo_tag}"
+    then
+        exit 1
+    fi
+
+    echo
+    echo 'Remove repository info tag from Docker container:'
+    if ! docker rmi "${repo_tag}"
+    then
+        exit 1
+    fi
+done
 
 
 echo 'Docker container image upload to gitlab registry complete'
