[#4]: set project name to ensure containers are stopped properly

diff --git a/code/bin/dd-dt-run-comp b/code/bin/dd-dt-run-comp
--- a/code/bin/dd-dt-run-comp
+++ b/code/bin/dd-dt-run-comp
@@ -57,7 +57,7 @@ echo
 
 # shellcheck disable=SC2034
 attrs=(comp_name gitlab_password gitlab_reg_url gitlab_username
-       path_to_comp_file)
+       path_to_comp_file project_name)
 # shellcheck disable=SC2034
 opt_attrs=()
 
@@ -95,18 +95,33 @@ fi
 
 echo
 
+# NOTE: must set project_name, otherwise docker-compose derives it from the
+# directory the docker-compose file is in; that directory is temporary
+# (e.g. /tmp/tmp.ojhzH2xyG4), so docker-compose is unable to associate
+# containers to be stopped by 'docker-compose down' with those started by
+# 'docker-compose up'; in consequence, containers are not stopped and
+# 'docker-compose down' fails with
+#   Removing network net-nginx-proxy
+#   error while removing network: ...
+#    ... network net-nginx-proxy id <id> has active endpoints
+# NOTE: project_name is persisted in com.docker.compose.project container label
+# NOTE: docker-compose is really picky about cmd line switch order
+# must carefully distinguish between docker-compose and command switches
+
 # https://docs.docker.com/compose/reference/down
 # TODO: add option to remove volumes
 echo "bring down ${comp_name}:"
-if ! docker-compose --file "${path_to_comp_file}" down
+if ! docker-compose --file         "${path_to_comp_file}"       \
+                    --project-name "${project_name}" down
 then
     exit 1
 fi
 
 # https://docs.docker.com/compose/reference/up
 echo "bring up ${comp_name}:"
-# NOTE: --detach must come last
-if ! docker-compose --file "${path_to_comp_file}" up --detach
+if ! docker-compose --file         "${path_to_comp_file}"       \
+                    --project-name "${project_name}" up         \
+                    --detach
 then
     exit 1
 fi
