[#4]: delete configured container volumes if they exist; review output

diff --git a/code/bin/dd-dt-run-image b/code/bin/dd-dt-run-image
--- a/code/bin/dd-dt-run-image
+++ b/code/bin/dd-dt-run-image
@@ -11,7 +11,7 @@
 
 # NOTE: see also dd-dt-build-cont-comps
 
-# TODO: this doesn't run an image, but a container --> rename script
+# TODO: this doesn't run an image, but a container --> rename script ?
 
 echo
 echo 'run a Docker container image'
@@ -103,6 +103,25 @@ else
     exit 1
 fi
 
+# TODO: in theory, this should be simpler by filtering by name; in practice,
+# the docker name filter "matches on all or part of a volume’s name.":
+# https://docs.docker.com/engine/reference/commandline/volume_ls/#filtering
+# therefore, the filter could match false positives if one volume's name
+# is part of another volume's name --> need to do this manually :-(
+if [ "${volumes}" != 'null' ]
+then
+    echo -n 'Get list of existing volumes: '
+    if output="$(docker volume ls --format '{{.Name}}' 2>&1)"
+    then
+        echo 'OK'
+        mapfile -t exist_volumes <<< "${output}"
+    else
+        echo 'ERROR'
+        echo "${output}"
+        exit 1
+    fi
+fi
+
 
 # check if a container with that name is running
 # NOTE: the usual simple approach fails for e.g. ci-postgres
@@ -123,7 +142,7 @@ done
 
 if [ "${cont_exists}" = true ]
 then
-    echo -n 'Stop running container: '
+    echo -n "Stop running container ${cont_name}: "
     if output="$(docker stop "${cont_name}" 2>&1)"
     then
         echo 'OK'
@@ -152,7 +171,7 @@ done
 
 if [ "${cont_exists}" = true ]
 then
-    echo -n 'Remove existing container: '
+    echo -n "Remove running container ${cont_name}: "
     if output="$(docker rm "${cont_name}" 2>&1)"
     then
         echo 'OK'
@@ -163,6 +182,30 @@ then
     fi
 fi
 
+if [ "${volumes}" != 'null' ]
+then
+    for line in $(jq -cr '.[] | @base64' <<< "${volumes}")
+    do
+        vol_conf="$(base64 --decode <<< "${line}")"
+        source="$(jq -r '.source' <<< "${vol_conf}")"
+        target="$(jq -r '.target' <<< "${vol_conf}")"
+
+        # NOTE: test if string in array:
+        # https://stackoverflow.com/a/47541882
+        if printf '%s\n' "${exist_volumes[@]}"  | grep -q "^${source}$"
+        then
+            echo -n "Remove existing volume ${source}: "
+            if output="$(docker volume rm "${source}" 2>&1)"
+            then
+                echo 'OK'
+            else
+                echo 'ERROR'
+                echo "${output}"
+                exit 1
+            fi
+        fi
+    done
+fi
 
 declare -a docker_args=('--detach')
 
