[#2]: prepend dd- to script names to align with corporate conventions;
done with

$ cd "${HOME}/DevBase/DesmoDyne/Tools/DockerTools/code/bin"
$ for old_name in *
  do
    new_name="dd-${old_name}"
    echo "old name: ${old_name}"
    echo "new name: ${new_name}"
    sed -e "s|${old_name}|${new_name}|g" "${old_name}" > "${new_name}"
    rm "${old_name}"
    echo
    echo
    echo
  done
$ cd - > /dev/null

diff --git a/code/bin/dd-download-cont-images-from-aws b/code/bin/dd-download-cont-images-from-aws
--- a/code/bin/dd-download-cont-images-from-aws
+++ b/code/bin/dd-download-cont-images-from-aws
@@ -1,28 +1,24 @@
 #!/usr/bin/env bash
 
-# upload-cont-images-to-aws
+# dd-download-cont-images-from-aws
 #
-# upload Docker container images to AWS registry
+# download Docker container images from AWS registry
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
-# created : 2018-10-07
+# created : 2018-12-23
 
 
-# https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html
-# NOTE: see also build-cont-comps
+# NOTE: see also build-cont-comps and upload-cont-images-to-aws
 
 
 echo
-echo 'upload Docker container images to AWS registry'
+echo 'download Docker container images from AWS registry'
 echo
 
 
 # -----------------------------------------------------------------------------
 # configure script parameters
-
-# NOTE: I would have thought that these variables are already defined if this
-# script is called as a subscript by build; that does not seem to be the case
 
 # path from this script to project root
 path_to_proj_root='../..'
@@ -41,7 +37,6 @@ path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 # https://github.com/koalaman/shellcheck/wiki/SC2034
 
 # array with alphabetical list of tools called by this script
-# NOTE: too late to test for realpath, already used above
 # shellcheck disable=SC2034
 req_tools=('aws' 'docker' 'jq' 'yq')
 
@@ -52,9 +47,6 @@ ext_paths=()
 
 # -----------------------------------------------------------------------------
 # load BashLib
-
-# NOTE: I just assumed BashLib would already be available here if this script
-# is called as subscript to build, as build sources it, but this is not true
 
 # NOTE: this only tests if library can be sourced;
 # functions are only defined in "$(...)" subshell,
@@ -83,13 +75,6 @@ if ! get_conf_file_arg "${@}"        ; then exit 1; fi
 # load script configuration
 
 # NOTE: see config file for parameter documentation
-# TODO: refactor this out to BashLib function
-# TODO: error handling, e.g. check if json / yaml keys are available
-# TODO: get this to work with latest yq 2.x
-
-# NOTE: this essentially converts YAML to JSON
-# conf_file is defined by proc_cmd_line_args
-# https://github.com/koalaman/shellcheck/wiki/SC2154
 # shellcheck disable=SC2154
 conf="$(yq r -j "${conf_file}")"
 
@@ -109,16 +94,10 @@ aws="aws --profile ${aws_profile}"
 
 
 # -----------------------------------------------------------------------------
-# upload Docker container images to AWS registry
+# download Docker container images from AWS registry
 
 echo
 
-# http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_GetStarted.html
-# http://docs.aws.amazon.com/cli/latest/reference/ecr/index.html
-
-# NOTE: this requires local credentials
-# usually stored in ~/.aws/credentials
-# and created using 'aws configure'
 echo -n 'Log into AWS: '
 if output="$(${aws} ecr get-login --no-include-email \
                                   --region "${aws_def_region}" 2>&1)"
@@ -136,13 +115,9 @@ if output="$(${login_command} 2>&1)"
 then
     echo 'OK'
 
-    # TODO: look into output:
-    # WARNING! Using --password via the CLI is insecure. Use --password-stdin.
-    # Login Succeeded
     if [ -n "${output}" ]
     then
         echo "${output}"
-        echo
     fi
 else
     echo 'ERROR'
@@ -150,33 +125,10 @@ else
     exit 1
 fi
 
-echo -n 'Get existing container image repositories: '
-if output="$(${aws} ecr describe-repositories 2>&1)"
-then
-    echo 'OK'
-    repo_json="${output}"
-    echo
-else
-    echo 'ERROR'
-    echo "${output}"
-    exit 1
-fi
-
-if ! existing_repo_uris="$(jq -r '.repositories[].repositoryUri' \
-                             <<< "${repo_json}")"
-then
-    exit 1
-fi
-
-
 if ! image_names="$(jq -r 'keys[]' <<< "${image_confs}" | sort)"
 then
     exit 1
 fi
-
-# TODO: review log output when there are no images
-# TODO: continue or exit ?
-# TODO: review error handling / output / exit code
 
 for image_name in ${image_names}
 do
@@ -195,77 +147,42 @@ do
         exit 1
     fi
 
-    # TODO: introduce image versioning
     repo_uri="${aws_reg_url}/${aws_namespace}/${image_name}"
     repo_tag="${repo_uri}:${image_tag}"
     local_tag="${local_namespace}/${image_name}:${image_tag}"
 
-    # create container image repo if required
-    # NOTE: the usual simple approach fails for e.g. ci-postgres
-    # if they are part of another URI, e.g. ci-postgres-sonarqube
-    # https://stackoverflow.com/a/229606
-
-    repo_exists=false
-
-    for existing_repo_uri in ${existing_repo_uris}
-    do
-        if [ "${existing_repo_uri}" = "${repo_uri}" ]
-        then
-            repo_exists=true
-            break
-        fi
-    done
-
-    if [ "${repo_exists}" = false ]
+    echo "pull ${repo_tag}:"
+    if ! docker pull "${repo_tag}"
     then
-        echo -n 'Create container image repository: '
-        if output="$(${aws} ecr create-repository \
-                      --repository-name "${aws_namespace}/${image_name}" 2>&1)"
-        then
-            echo 'OK'
-            echo
-        else
-            echo 'ERROR'
-            echo "${output}"
-            exit 1
-        fi
+        exit 1
     fi
 
-    echo -n 'Tag Docker container image with repository info: '
-    if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
+    echo
+    echo -n 'Create Docker container image non-repository tag: '
+    if output="$(docker tag "${repo_tag}" "${local_tag}" 2>&1)"
     then
         echo 'OK'
-        echo
     else
         echo 'ERROR'
         echo "${output}"
         exit 1
     fi
 
-
-    # NOTE: docker push displays its own output
-    # TODO: using official url here fails with
-    #   Get https://registry.desmodyne.com/v2/: x509: certificate is valid for
-    #     *.dkr.ecr.eu-central-1.amazonaws.com, not registry.desmodyne.com
-    echo 'Push Docker container image to repository:'
-    if ! docker push "${repo_tag}"
+    echo -n 'Delete Docker container image with repository tag: '
+    if output="$(docker rmi "${repo_tag}" 2>&1)"
     then
-        exit 1
-    fi
-
-    # NOTE: docker push displays its own output
-    echo
-    echo 'Remove repository info tag from Docker container:'
-    if ! docker rmi "${repo_tag}"
-    then
+        echo 'OK'
+    else
+        echo 'ERROR'
+        echo "${output}"
         exit 1
     fi
 
     echo
-    echo "container image ${image_name} upload complete"
+    echo "container image ${image_name} download complete"
     echo
 done
 
 
-echo 'Docker container image upload to AWS registry complete'
+echo 'Docker container image download from AWS registry complete'
 echo
diff --git a/code/bin/dd-upload-cont-images-to-aws b/code/bin/dd-upload-cont-images-to-aws
--- a/code/bin/dd-upload-cont-images-to-aws
+++ b/code/bin/dd-upload-cont-images-to-aws
@@ -1,25 +1,28 @@
 #!/usr/bin/env bash
 
-# upload-cont-images-to-gitlab
+# dd-upload-cont-images-to-aws
 #
-# upload Docker container images to gitlab registry
+# upload Docker container images to AWS registry
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
-# created : 2019-01-20
+# created : 2018-10-07
 
 
-# https://gitlab.com/help/user/project/container_registry
+# https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html
 # NOTE: see also build-cont-comps
 
 
 echo
-echo 'upload Docker container images to gitlab registry'
+echo 'upload Docker container images to AWS registry'
 echo
 
 
 # -----------------------------------------------------------------------------
 # configure script parameters
+
+# NOTE: I would have thought that these variables are already defined if this
+# script is called as a subscript by build; that does not seem to be the case
 
 # path from this script to project root
 path_to_proj_root='../..'
@@ -40,7 +43,7 @@ path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 # array with alphabetical list of tools called by this script
 # NOTE: too late to test for realpath, already used above
 # shellcheck disable=SC2034
-req_tools=('docker' 'jq' 'yq')
+req_tools=('aws' 'docker' 'jq' 'yq')
 
 # array with paths to append to PATH
 # shellcheck disable=SC2034
@@ -90,26 +93,52 @@ if ! get_conf_file_arg "${@}"        ; then exit 1; fi
 # shellcheck disable=SC2154
 conf="$(yq r -j "${conf_file}")"
 
-gitlab_namespace="$(jq -r '.gitlab_namespace'  <<< "${conf}")"
-gitlab_reg_url="$(  jq -r '.gitlab_reg_url'    <<< "${conf}")"
-image_confs="$(     jq -r '.images'            <<< "${conf}")"
-local_namespace="$( jq -r '.local_namespace'   <<< "${conf}")"
+aws_def_region="$( jq -r '.aws_def_region'    <<< "${conf}")"
+aws_namespace="$(  jq -r '.aws_namespace'     <<< "${conf}")"
+aws_profile="$(    jq -r '.aws_profile'       <<< "${conf}")"
+aws_reg_url="$(    jq -r '.aws_reg_url'       <<< "${conf}")"
+image_confs="$(    jq -r '.images'            <<< "${conf}")"
+local_namespace="$(jq -r '.local_namespace'   <<< "${conf}")"
 
 
 # -----------------------------------------------------------------------------
-# upload Docker container images to gitlab registry
+# configure script parameters, cont.
+
+# command shortcut for shorter code
+aws="aws --profile ${aws_profile}"
+
+
+# -----------------------------------------------------------------------------
+# upload Docker container images to AWS registry
 
 echo
 
-# https://docs.docker.com/engine/reference/commandline/login
+# http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_GetStarted.html
+# http://docs.aws.amazon.com/cli/latest/reference/ecr/index.html
 
-# TODO: this only works if macOS Keychain contains credentials
-# https://docs.docker.com/engine/reference/commandline/login/#credentials-store
-echo -n 'Log into gitlab Docker repository: '
-if output="$(docker login "${gitlab_reg_url}" 2>&1)"
+# NOTE: this requires local credentials
+# usually stored in ~/.aws/credentials
+# and created using 'aws configure'
+echo -n 'Log into AWS: '
+if output="$(${aws} ecr get-login --no-include-email \
+                                  --region "${aws_def_region}" 2>&1)"
+then
+    echo 'OK'
+    login_command="${output}"
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
+
+echo -n 'Log into AWS Docker repository: '
+if output="$(${login_command} 2>&1)"
 then
     echo 'OK'
 
+    # TODO: look into output:
+    # WARNING! Using --password via the CLI is insecure. Use --password-stdin.
+    # Login Succeeded
     if [ -n "${output}" ]
     then
         echo "${output}"
@@ -121,10 +150,24 @@ else
     exit 1
 fi
 
-# NOTE: on AWS, the container registry is structured globally per AWS account
-# as a list of repositories and a repository must be created for every image;
-# on gitlab, the container registry is structured per project and one
-# repository exists per project; not need to create it to upload and image
+echo -n 'Get existing container image repositories: '
+if output="$(${aws} ecr describe-repositories 2>&1)"
+then
+    echo 'OK'
+    repo_json="${output}"
+    echo
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
+
+if ! existing_repo_uris="$(jq -r '.repositories[].repositoryUri' \
+                             <<< "${repo_json}")"
+then
+    exit 1
+fi
+
 
 if ! image_names="$(jq -r 'keys[]' <<< "${image_confs}" | sort)"
 then
@@ -153,9 +196,40 @@ do
     fi
 
     # TODO: introduce image versioning
-    repo_uri="${gitlab_reg_url}/${gitlab_namespace}/${image_name}"
+    repo_uri="${aws_reg_url}/${aws_namespace}/${image_name}"
     repo_tag="${repo_uri}:${image_tag}"
     local_tag="${local_namespace}/${image_name}:${image_tag}"
+
+    # create container image repo if required
+    # NOTE: the usual simple approach fails for e.g. ci-postgres
+    # if they are part of another URI, e.g. ci-postgres-sonarqube
+    # https://stackoverflow.com/a/229606
+
+    repo_exists=false
+
+    for existing_repo_uri in ${existing_repo_uris}
+    do
+        if [ "${existing_repo_uri}" = "${repo_uri}" ]
+        then
+            repo_exists=true
+            break
+        fi
+    done
+
+    if [ "${repo_exists}" = false ]
+    then
+        echo -n 'Create container image repository: '
+        if output="$(${aws} ecr create-repository \
+                      --repository-name "${aws_namespace}/${image_name}" 2>&1)"
+        then
+            echo 'OK'
+            echo
+        else
+            echo 'ERROR'
+            echo "${output}"
+            exit 1
+        fi
+    fi
 
     echo -n 'Tag Docker container image with repository info: '
     if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
@@ -193,5 +267,5 @@ do
 done
 
 
-echo 'Docker container image upload to gitlab registry complete'
+echo 'Docker container image upload to AWS registry complete'
 echo
diff --git a/code/bin/dd-upload-cont-images-to-gitlab b/code/bin/dd-upload-cont-images-to-gitlab
--- a/code/bin/dd-upload-cont-images-to-gitlab
+++ b/code/bin/dd-upload-cont-images-to-gitlab
@@ -1,19 +1,20 @@
 #!/usr/bin/env bash
 
-# download-cont-images-from-aws
+# dd-upload-cont-images-to-gitlab
 #
-# download Docker container images from AWS registry
+# upload Docker container images to gitlab registry
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
-# created : 2018-12-23
+# created : 2019-01-20
 
 
-# NOTE: see also build-cont-comps and upload-cont-images-to-aws
+# https://gitlab.com/help/user/project/container_registry
+# NOTE: see also build-cont-comps
 
 
 echo
-echo 'download Docker container images from AWS registry'
+echo 'upload Docker container images to gitlab registry'
 echo
 
 
@@ -37,8 +38,9 @@ path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 # https://github.com/koalaman/shellcheck/wiki/SC2034
 
 # array with alphabetical list of tools called by this script
+# NOTE: too late to test for realpath, already used above
 # shellcheck disable=SC2034
-req_tools=('aws' 'docker' 'jq' 'yq')
+req_tools=('docker' 'jq' 'yq')
 
 # array with paths to append to PATH
 # shellcheck disable=SC2034
@@ -47,6 +49,9 @@ ext_paths=()
 
 # -----------------------------------------------------------------------------
 # load BashLib
+
+# NOTE: I just assumed BashLib would already be available here if this script
+# is called as subscript to build, as build sources it, but this is not true
 
 # NOTE: this only tests if library can be sourced;
 # functions are only defined in "$(...)" subshell,
@@ -75,49 +80,40 @@ if ! get_conf_file_arg "${@}"        ; then exit 1; fi
 # load script configuration
 
 # NOTE: see config file for parameter documentation
+# TODO: refactor this out to BashLib function
+# TODO: error handling, e.g. check if json / yaml keys are available
+# TODO: get this to work with latest yq 2.x
+
+# NOTE: this essentially converts YAML to JSON
+# conf_file is defined by proc_cmd_line_args
+# https://github.com/koalaman/shellcheck/wiki/SC2154
 # shellcheck disable=SC2154
 conf="$(yq r -j "${conf_file}")"
 
-aws_def_region="$( jq -r '.aws_def_region'    <<< "${conf}")"
-aws_namespace="$(  jq -r '.aws_namespace'     <<< "${conf}")"
-aws_profile="$(    jq -r '.aws_profile'       <<< "${conf}")"
-aws_reg_url="$(    jq -r '.aws_reg_url'       <<< "${conf}")"
-image_confs="$(    jq -r '.images'            <<< "${conf}")"
-local_namespace="$(jq -r '.local_namespace'   <<< "${conf}")"
+gitlab_namespace="$(jq -r '.gitlab_namespace'  <<< "${conf}")"
+gitlab_reg_url="$(  jq -r '.gitlab_reg_url'    <<< "${conf}")"
+image_confs="$(     jq -r '.images'            <<< "${conf}")"
+local_namespace="$( jq -r '.local_namespace'   <<< "${conf}")"
 
 
 # -----------------------------------------------------------------------------
-# configure script parameters, cont.
-
-# command shortcut for shorter code
-aws="aws --profile ${aws_profile}"
-
-
-# -----------------------------------------------------------------------------
-# download Docker container images from AWS registry
+# upload Docker container images to gitlab registry
 
 echo
 
-echo -n 'Log into AWS: '
-if output="$(${aws} ecr get-login --no-include-email \
-                                  --region "${aws_def_region}" 2>&1)"
-then
-    echo 'OK'
-    login_command="${output}"
-else
-    echo 'ERROR'
-    echo "${output}"
-    exit 1
-fi
+# https://docs.docker.com/engine/reference/commandline/login
 
-echo -n 'Log into AWS Docker repository: '
-if output="$(${login_command} 2>&1)"
+# TODO: this only works if macOS Keychain contains credentials
+# https://docs.docker.com/engine/reference/commandline/login/#credentials-store
+echo -n 'Log into gitlab Docker repository: '
+if output="$(docker login "${gitlab_reg_url}" 2>&1)"
 then
     echo 'OK'
 
     if [ -n "${output}" ]
     then
         echo "${output}"
+        echo
     fi
 else
     echo 'ERROR'
@@ -125,10 +121,19 @@ else
     exit 1
 fi
 
+# NOTE: on AWS, the container registry is structured globally per AWS account
+# as a list of repositories and a repository must be created for every image;
+# on gitlab, the container registry is structured per project and one
+# repository exists per project; not need to create it to upload and image
+
 if ! image_names="$(jq -r 'keys[]' <<< "${image_confs}" | sort)"
 then
     exit 1
 fi
+
+# TODO: review log output when there are no images
+# TODO: continue or exit ?
+# TODO: review error handling / output / exit code
 
 for image_name in ${image_names}
 do
@@ -147,42 +152,46 @@ do
         exit 1
     fi
 
-    repo_uri="${aws_reg_url}/${aws_namespace}/${image_name}"
+    # TODO: introduce image versioning
+    repo_uri="${gitlab_reg_url}/${gitlab_namespace}/${image_name}"
     repo_tag="${repo_uri}:${image_tag}"
     local_tag="${local_namespace}/${image_name}:${image_tag}"
 
-    echo "pull ${repo_tag}:"
-    if ! docker pull "${repo_tag}"
-    then
-        exit 1
-    fi
-
-    echo
-    echo -n 'Create Docker container image non-repository tag: '
-    if output="$(docker tag "${repo_tag}" "${local_tag}" 2>&1)"
+    echo -n 'Tag Docker container image with repository info: '
+    if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
     then
         echo 'OK'
+        echo
     else
         echo 'ERROR'
         echo "${output}"
         exit 1
     fi
 
-    echo -n 'Delete Docker container image with repository tag: '
-    if output="$(docker rmi "${repo_tag}" 2>&1)"
+
+    # NOTE: docker push displays its own output
+    # TODO: using official url here fails with
+    #   Get https://registry.desmodyne.com/v2/: x509: certificate is valid for
+    #     *.dkr.ecr.eu-central-1.amazonaws.com, not registry.desmodyne.com
+    echo 'Push Docker container image to repository:'
+    if ! docker push "${repo_tag}"
     then
-        echo 'OK'
-    else
-        echo 'ERROR'
-        echo "${output}"
+        exit 1
+    fi
+
+    # NOTE: docker push displays its own output
+    echo
+    echo 'Remove repository info tag from Docker container:'
+    if ! docker rmi "${repo_tag}"
+    then
         exit 1
     fi
 
     echo
-    echo "container image ${image_name} download complete"
+    echo "container image ${image_name} upload complete"
     echo
 done
 
 
-echo 'Docker container image download from AWS registry complete'
+echo 'Docker container image upload to gitlab registry complete'
 echo
