[#3]: push image with both stage and commit/semver tags

diff --git a/code/bin/dd-upload-cont-images-to-gitlab b/code/bin/dd-upload-cont-images-to-gitlab
--- a/code/bin/dd-upload-cont-images-to-gitlab
+++ b/code/bin/dd-upload-cont-images-to-gitlab
@@ -122,38 +122,47 @@ do
         exit 1
     fi
 
-    if ! image_tag="$(jq -r '.image_tag' <<< "${image_conf}")"
+    if ! image_tag_stage="$( jq -r '.image_tag_stage'  <<< "${image_conf}")"
+    then
+        exit 1
+    fi
+
+    if ! image_tag_commit="$(jq -r '.image_tag_commit' <<< "${image_conf}")"
     then
         exit 1
     fi
 
     repo_uri="${gitlab_reg_url}/${gitlab_namespace}/${image_name}"
-    repo_tag="${repo_uri}:${image_tag}"
-    local_tag="${local_namespace}/${image_name}:${image_tag}"
 
-    echo -n 'Tag Docker container image with repository info: '
-    if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
-    then
-        echo 'OK'
+    for image_tag in "${image_tag_stage}" "${image_tag_commit}"
+    do
+        repo_tag="${repo_uri}:${image_tag}"
+        local_tag="${local_namespace}/${image_name}:${image_tag}"
+
+        echo -n 'Tag Docker container image with repository info: '
+        if output="$(docker tag "${local_tag}" "${repo_tag}" 2>&1)"
+        then
+            echo 'OK'
+            echo
+        else
+            echo 'ERROR'
+            echo "${output}"
+            exit 1
+        fi
+
+        echo 'Push Docker container image to repository:'
+        if ! docker push "${repo_tag}"
+        then
+            exit 1
+        fi
+
         echo
-    else
-        echo 'ERROR'
-        echo "${output}"
-        exit 1
-    fi
-
-    echo 'Push Docker container image to repository:'
-    if ! docker push "${repo_tag}"
-    then
-        exit 1
-    fi
-
-    echo
-    echo 'Remove repository info tag from Docker container:'
-    if ! docker rmi "${repo_tag}"
-    then
-        exit 1
-    fi
+        echo 'Remove repository info tag from Docker container:'
+        if ! docker rmi "${repo_tag}"
+        then
+            exit 1
+        fi
+    done
 
     echo
     echo "container image ${image_name} upload complete"
