[#3]: review shellcheck issues

diff --git a/cicd/bin/upload b/cicd/bin/upload
--- a/cicd/bin/upload
+++ b/cicd/bin/upload
@@ -51,7 +51,6 @@ curl_args=('--show-error' '--silent')
 # shellcheck disable=SC1090
 if output="$(source "${path_to_bashlib}" 2>&1)"
 then
-    # shellcheck disable=SC1090
     source "${path_to_bashlib}"
 else
     echo "${output}"
@@ -79,10 +78,12 @@ path_to_conf_file="${path_to_proj_root}/${path_to_conf_file}"
 # -----------------------------------------------------------------------------
 # load script configuration
 
+# shellcheck disable=SC2034
 attrs=(archive_path archive_tmpl brew_formula brew_repo_github_url
        formula_folder homepage
        git_ci_email git_ci_user git_msg_tmpl github_branch github_repo_url
        path_to_brew_repo path_to_brew_tmpl path_to_local_tmp)
+# shellcheck disable=SC2034
 opt_attrs=()
 
 echo
@@ -145,9 +146,11 @@ fi
 
 # NOTE: depending on gitlab CI/CD configuration, repo might be in detached head
 # TODO: repo_info > branch seems to be HEAD at times and master at other times
+# shellcheck disable=SC2154
 ref_spec="HEAD:${github_branch}"
 
 echo -n "push repository ${github_branch} branch to github: "
+# shellcheck disable=SC2154
 if output="$(git push "${github_repo_url}" "${ref_spec}" 2>&1)"
 then
     echo 'OK'
@@ -178,11 +181,17 @@ then
     mkdir -p "${path_to_local_tmp}"
 fi
 
+# shellcheck disable=SC2059,SC2154
 archive_file="$(printf "${archive_tmpl}" "${semver}")"
+# shellcheck disable=SC2154
 archive_url="${homepage}/${archive_path}/${archive_file}"
 
 # https://stackoverflow.com/a/16363115
-pushd "${path_to_local_tmp}" > /dev/null
+if ! pushd "${path_to_local_tmp}" > /dev/null
+then
+    echo "Failed to pushd to local temp folder ${path_to_local_tmp}"
+    exit 1
+fi
 
 echo -n 'download release archive: '
 # NOTE: -L is required to follow redirections
@@ -195,7 +204,11 @@ else
     exit 1
 fi
 
-popd > /dev/null
+if ! popd > /dev/null
+then
+    echo "Failed to popd from local temp folder ${path_to_local_tmp}"
+    exit 1
+fi
 
 echo -n 'get release archive sha256 sum: '
 if output="$(sha256sum "${path_to_local_tmp}/${archive_file}" 2>&1)"
@@ -208,7 +221,10 @@ else
     exit 1
 fi
 
+# NOTE: these are not bash, but jq variables
+# shellcheck disable=SC2016
 json_tmpl='{ "archive_url": $archive_url, "homepage": '
+# shellcheck disable=SC2016
 json_tmpl+='$homepage, "sha256_sum": $sha256_sum }'
 
 tmpl_data="$(jq -n --arg archive_url "${archive_url}"   \
@@ -216,6 +232,7 @@ tmpl_data="$(jq -n --arg archive_url "${archive_url}"   \
                    --arg sha256_sum  "${sha256_sum}" "${json_tmpl}")"
 
 echo -n 'render brew formula template: '
+# shellcheck disable=SC2154
 if output="$(jinja2 --format=json                                       \
                     --outfile="${path_to_local_tmp}/${brew_formula}"    \
                     --strict "${path_to_brew_tmpl}" <<< "${tmpl_data}" 2>&1)"
@@ -241,6 +258,7 @@ echo
 if [ -d "${path_to_brew_repo}" ]
 then
     echo 'update brew formula repository:'
+    # shellcheck disable=SC2154
     if ! git -C "${path_to_brew_repo}" fetch "${brew_repo_github_url}" &&
          git -C "${path_to_brew_repo}" pull  "${brew_repo_github_url}"
     then
@@ -256,6 +274,7 @@ else
     # TODO: use ReleaseTools > dd-rt-verify-user-configuration for this
     # TODO: no output if successful, no idea about output if error
     echo -n 'configure git user and email: '
+    # shellcheck disable=SC2154
     if git -C "${path_to_brew_repo}" config user.email "${git_ci_email}" &&
        git -C "${path_to_brew_repo}" config user.name  "${git_ci_user}"
     then
@@ -273,6 +292,7 @@ fi
 echo
 
 echo -n 'copy brew formula to repository: '
+# shellcheck disable=SC2154
 if output="$(cp "${path_to_local_tmp}/${brew_formula}"     \
                 "${path_to_brew_repo}/${formula_folder}/" 2>&1)"
 then
@@ -294,6 +314,7 @@ else
     exit 1
 fi
 
+# shellcheck disable=SC2059,SC2154
 git_msg="$(printf "${git_msg_tmpl}" "${semver}")"
 
 echo -n 'commit brew formula to repository: '
